
#cloud-config
manage_etc_hosts: true

groups: docker

hostname: "${server_name}-${current_server}"

apt:
  sources:
    docker.list:
      source: 'deb [arch=amd64] https://download.docker.com/linux/${distrib} $RELEASE stable'
      keyid: 0EBFCD88

packages:
  - debian-archive-keyring
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - htop
  - docker-ce
  - fail2ban
  - screen

timezone: Europe/Amsterdam
disable_root: true
locale: en_US.UTF-8
ssh_genkeytypes:
  - rsa
  - ed25519

users:
  - name: ${user}
    gecos: ${user}
    primary_group: ${user}
    groups: sudo, docker
    ssh-authorized-keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKeenMxgDoiTdaYOS54kdYmPcEquyhI8MunbeO0G0tjw bram@pescheck.nl"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAK/4fjkmFjL3oYDP4DWO+IcpyhUMf9G9a2ezsJCAwhz bram@pescheck.nl"
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    passwd: '*'
    lock_password: false

write_files:
  - owner: root:root
    path: /home/${user}/.openttd/openttd.cfg
    content: |
      [version]
      version_string = 12.1
      version_number = 1C186D64
      ini_version = 2

      [network]
      commands_per_frame = 2
      max_commands_in_queue = 16
      bytes_per_frame = 8
      bytes_per_frame_burst = 256
      max_init_time = 100
      max_join_time = 500
      max_download_time = 1000
      max_password_time = 2000
      max_lag_time = 500
      pause_on_join = false
      server_port = 3979
      server_admin_port = 3977
      server_admin_chat = true
      server_game_type = public
      autoclean_companies = false
      autoclean_unprotected = 12
      autoclean_protected = 36
      autoclean_novehicles = 0
      max_companies = 14
      max_clients = 16
      restart_game_year = 3000
      min_active_clients = 0
      reload_cfg = false
      no_http_content_downloads = false
      use_relay_service = ask

      [misc]
      display_opt = SHOW_TOWN_NAMES|SHOW_STATION_NAMES|SHOW_SIGNS|FULL_ANIMATION|FULL_DETAIL|WAYPOINTS|SHOW_COMPETITOR_SIGNS
      fullscreen = false
      video_hw_accel = true
      video_vsync = false
      support8bpp = no
      graphicsset = 
      soundsset = "NoSound"
      musicset = 
      videodriver = 
      musicdriver = 
      sounddriver = 
      blitter = 
      language = english_US.lng
      resolution = 1920,1017
      screenshot_format = 
      savegame_format = 
      rightclick_emulate = false
      small_font = 
      medium_font = 
      large_font = 
      mono_font = 
      small_size = 0
      medium_size = 0
      large_size = 0
      mono_size = 0
      small_aa = false
      medium_aa = false
      large_aa = false
      mono_aa = false
      sprite_cache_size_px = 128
      player_face = 0
      transparency_options = 0
      transparency_locks = 0
      invisibility_options = 0
      keyboard = 
      keyboard_caps = 
      last_newgrf_count = 0
      gui_zoom = -1
      font_zoom = -1

      [difficulty]
      max_no_competitors = 0
      number_towns = 2
      industry_density = 5
      max_loan = 300000
      initial_interest = 2
      vehicle_costs = 0
      competitor_speed = 2
      vehicle_breakdowns = 0
      subsidy_multiplier = 0
      subsidy_duration = 0
      construction_cost = 0
      terrain_type = 1
      quantity_sea_lakes = 0
      economy = false
      line_reverse_mode = false
      disasters = false
      town_council_tolerance = 0

      [economy]
      town_layout = 0
      allow_town_roads = true
      found_town = 0
      allow_town_level_crossings = true
      town_cargogen_mode = 1
      station_noise_level = false
      inflation = false
      multiple_industry_per_town = true
      bribe = true
      exclusive_rights = true
      fund_buildings = true
      fund_roads = true
      give_money = true
      type = 1
      allow_shares = false
      min_years_for_shares = 6
      feeder_payment_share = 75
      town_growth_rate = 2
      larger_towns = 4
      initial_city_size = 2
      mod_road_rebuild = true
      dist_local_authority = 20
      town_noise_population[0] = 800
      town_noise_population[1] = 2000
      town_noise_population[2] = 4000
      infrastructure_maintenance = false

      [order]
      no_servicing_if_no_breakdowns = true
      improved_load = true
      selectgoods = true
      serviceathelipad = true
      gradual_loading = true

      [station]
      never_expire_airports = true
      station_spread = 40
      modified_catchment = true
      serve_neutral_industries = true
      adjacent_stations = true
      distant_join_stations = true

      [vehicle]
      road_side = right
      train_acceleration_model = 1
      roadveh_acceleration_model = 1
      train_slope_steepness = 0
      roadveh_slope_steepness = 0
      max_train_length = 44
      smoke_amount = 1
      never_expire_vehicles = true
      max_trains = 500
      max_roadveh = 0
      max_aircraft = 0
      max_ships = 0
      wagon_speed_limits = true
      disable_elrails = false
      freight_trains = 1
      plane_speed = 4
      dynamic_engines = true
      plane_crashes = 0
      extend_vehicle_life = 0
      servint_ispercent = false
      servint_trains = 150
      servint_roadveh = 150
      servint_ships = 360
      servint_aircraft = 100

      [gui]
      autosave = monthly
      threaded_saves = true
      date_format_in_default_names = iso
      show_finances = true
      auto_scrolling = 0
      scroll_mode = 0
      smooth_scroll = false
      right_mouse_wnd_close = false
      measure_tooltip = true
      errmsg_duration = 5
      hover_delay_ms = 250
      osk_activation = double
      toolbar_pos = 1
      statusbar_pos = 1
      window_snap_radius = 10
      window_soft_limit = 20
      zoom_min = 0
      zoom_max = 5
      sprite_zoom_min = 0
      population_in_label = true
      link_terraform_toolbar = false
      smallmap_land_colour = 0
      liveries = 2
      starting_colour = 16
      auto_remove_signals = false
      prefer_teamchat = false
      scrollwheel_scrolling = 0
      scrollwheel_multiplier = 5
      pause_on_newgame = false
      advanced_vehicle_list = 1
      timetable_in_ticks = false
      timetable_arrival_departure = true
      quick_goto = true
      loading_indicators = 1
      default_rail_type = 0
      signal_gui_mode = 0
      coloured_news_year = 2000
      cycle_signal_types = 0
      drag_signals_density = 4
      drag_signals_fixed_distance = false
      semaphore_build_before = 1950
      vehicle_income_warn = true
      order_review_system = 2
      lost_vehicle_warn = true
      new_nonstop = true
      stop_location = 2
      keep_all_autosave = false
      autosave_on_exit = false
      autosave_on_network_disconnect = true
      max_num_autosaves = 16
      auto_euro = true
      news_message_timeout = 2
      show_track_reservation = true
      station_numtracks = 1
      station_platlength = 5
      station_dragdrop = true
      station_show_coverage = false
      persistent_buildingtools = true
      expenses_layout = true
      station_gui_group_order = 0
      station_gui_sort_by = 0
      station_gui_sort_order = 0
      missing_strings_threshold = 25
      graph_line_thickness = 3
      show_newgrf_name = false
      show_date_in_logs = false
      settings_restriction_mode = 0
      developer = 1
      newgrf_developer_tools = false
      ai_developer_tools = false
      scenario_developer = false
      newgrf_show_old_versions = false
      newgrf_default_palette = 1
      console_backlog_timeout = 100
      console_backlog_length = 100
      refresh_rate = 60
      fast_forward_speed_limit = 2500
      network_chat_box_width_pct = 40
      network_chat_box_height = 25
      network_chat_timeout = 20

      [locale]
      currency = GBP
      units_velocity = metric
      units_power = metric
      units_weight = metric
      units_volume = metric
      units_force = si
      units_height = metric
      digit_group_separator = 
      digit_group_separator_currency = 
      digit_decimal_separator = 

      [sound]
      news_ticker = true
      news_full = true
      new_year = true
      confirm = true
      click_beep = true
      disaster = true
      vehicle = true
      ambient = true

      [music]
      playlist = 0
      music_vol = 50
      effect_vol = 100
      custom_1 = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
      custom_2 = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
      playing = true
      shuffle = false

      [news_display]
      arrival_player = full
      arrival_other = summarized
      accident = full
      company_info = full
      open = summarized
      close = summarized
      economy = full
      production_player = summarized
      production_other = off
      production_nobody = off
      advice = full
      new_vehicles = full
      acceptance = full
      subsidies = summarized
      general = full

      [pf]
      forbid_90_deg = false
      roadveh_queue = true
      pathfinder_for_trains = 2
      pathfinder_for_roadvehs = 2
      pathfinder_for_ships = 2
      reverse_at_signals = false
      wait_oneway_signal = 15
      wait_twoway_signal = 41
      wait_for_pbs_path = 30
      reserve_paths = false
      path_backoff_interval = 20
      npf.npf_max_search_nodes = 10000
      npf.npf_rail_firstred_penalty = 1000
      npf.npf_rail_firstred_exit_penalty = 10000
      npf.npf_rail_lastred_penalty = 1000
      npf.npf_rail_station_penalty = 100
      npf.npf_rail_slope_penalty = 100
      npf.npf_rail_curve_penalty = 100
      npf.npf_rail_depot_reverse_penalty = 5000
      npf.npf_rail_pbs_cross_penalty = 300
      npf.npf_rail_pbs_signal_back_penalty = 1500
      npf.npf_buoy_penalty = 200
      npf.npf_water_curve_penalty = 100
      npf.npf_road_curve_penalty = 100
      npf.npf_crossing_penalty = 300
      npf.npf_road_drive_through_penalty = 800
      npf.npf_road_dt_occupied_penalty = 800
      npf.npf_road_bay_occupied_penalty = 1500
      npf.maximum_go_to_depot_penalty = 2000
      yapf.disable_node_optimization = false
      yapf.max_search_nodes = 10000
      yapf.rail_firstred_twoway_eol = false
      yapf.rail_firstred_penalty = 1000
      yapf.rail_firstred_exit_penalty = 10000
      yapf.rail_lastred_penalty = 1000
      yapf.rail_lastred_exit_penalty = 10000
      yapf.rail_station_penalty = 1000
      yapf.rail_slope_penalty = 200
      yapf.rail_curve45_penalty = 100
      yapf.rail_curve90_penalty = 600
      yapf.rail_depot_reverse_penalty = 5000
      yapf.rail_crossing_penalty = 300
      yapf.rail_look_ahead_max_signals = 10
      yapf.rail_look_ahead_signal_p0 = 500
      yapf.rail_look_ahead_signal_p1 = -100
      yapf.rail_look_ahead_signal_p2 = 5
      yapf.rail_pbs_cross_penalty = 300
      yapf.rail_pbs_station_penalty = 800
      yapf.rail_pbs_signal_back_penalty = 1500
      yapf.rail_doubleslip_penalty = 100
      yapf.rail_longer_platform_penalty = 800
      yapf.rail_longer_platform_per_tile_penalty = 0
      yapf.rail_shorter_platform_penalty = 4000
      yapf.rail_shorter_platform_per_tile_penalty = 0
      yapf.road_slope_penalty = 200
      yapf.road_curve_penalty = 100
      yapf.road_crossing_penalty = 300
      yapf.road_stop_penalty = 800
      yapf.road_stop_occupied_penalty = 800
      yapf.road_stop_bay_occupied_penalty = 1500
      yapf.maximum_go_to_depot_penalty = 2000
      yapf.ship_curve45_penalty = 100
      yapf.ship_curve90_penalty = 600

      [script]
      settings_profile = easy
      script_max_opcode_till_suspend = 10000
      script_max_memory_megabytes = 1024

      [ai]
      ai_in_multiplayer = true
      ai_disable_veh_train = false
      ai_disable_veh_roadveh = false
      ai_disable_veh_aircraft = false
      ai_disable_veh_ship = false

      [game_creation]
      town_name = dutch
      landscape = temperate
      heightmap_height = 30
      snow_line_height = 10
      snow_coverage = 40
      desert_coverage = 50
      starting_year = 1950
      ending_year = 3000
      land_generator = 1
      oil_refinery_limit = 0
      tgen_smoothness = 0
      variety = 0
      generation_seed = 3385225969
      tree_placer = 2
      heightmap_rotation = 0
      se_flat_world_height = 1
      map_x = 11
      map_y = 11
      water_borders = 0
      custom_town_number = 1
      custom_terrain_type = 30
      custom_sea_level = 1
      min_river_length = 16
      river_route_random = 5
      amount_of_rivers = 1

      [construction]
      map_height_limit = 0
      build_on_slopes = true
      command_pause_level = 1
      terraform_per_64k_frames = 4194304
      terraform_frame_burst = 4096
      clear_per_64k_frames = 4194304
      clear_frame_burst = 4096
      tree_per_64k_frames = 4194304
      tree_frame_burst = 4096
      autoslope = true
      extra_dynamite = true
      max_bridge_length = 64
      max_bridge_height = 12
      max_tunnel_length = 64
      train_signal_side = 1
      road_stop_on_town_road = true
      road_stop_on_competitor_road = true
      raw_industry_construction = 1
      industry_platform = 1
      freeform_edges = true
      extra_tree_placement = 2
      
      [currency]
      rate = 1
      separator = "."
      to_euro = 0
      prefix = 
      suffix = " credits"

      [company]
      engine_renew = true
      engine_renew_months = 6
      engine_renew_money = 100000
      renew_keep_length = false

      [ai_players]
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730
      none = start_date=730

      [game_scripts]
      none = 

      [newgrf]

      [newgrf-static]

  - owner: root:root
    path: /home/${user}/.openttd/private.cfg
    content: |
      ; This file possibly contains private information which can identify you as person.
      [private]

      [network]
      client_name = pescheck
      server_name = -: pescheck.io/vacancies :- #${current_server} FLAT|TRAIN|NOBRK|1950-3000
      connect_to_ip = 
      last_joined = 
            
      [server_bind_addresses]

      [servers]

      [bans]

      [version]
      version_string = 12.1
      version_number = 1C186D64
      ini_version = 2

  - owner: root:root
    path: /home/${user}/.openttd/secrets.cfg
    content: |
      ; Do not share this file with others, not even if they claim to be technical support.
      ; This file contains saved passwords and other secrets that should remain private to you!
      [secrets]

      [network]
      server_password = 
      rcon_password = ${game_password}
      admin_password = ${game_password}
      default_company_pass = 
      network_id = 

      [version]
      version_string = 12.1
      version_number = 1C186D64
      ini_version = 2
  - owner: root:root
    path: /etc/systemd/system/docker.openttd.service
    content: |
      [Unit]
      Description=OpenTTD Service
      After=docker.service
      Requires=docker.service

      [Service]
      User=${user}
      Group=${user}
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=-/usr/bin/docker exec %n stop
      ExecStartPre=-/usr/bin/docker rm %n
      ExecStartPre=/usr/bin/docker pull bateau/openttd:latest
      ExecStart=/usr/bin/docker run \
        -p 3979:3979/tcp \
        -p 3979:3979/udp \
        -v /home/${user}/.openttd:/home/openttd/.openttd \
        --name %n \
        bateau/openttd:latest

      [Install]
      WantedBy=default.target

  - owner: root:root
    path: /etc/systemd/system/docker.openra.service
    content: |
      [Unit]
      Description=OpenRA Service
      After=docker.service
      Requires=docker.service

      [Service]
      User=${user}
      Group=${user}
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=-/usr/bin/docker exec %n stop
      ExecStartPre=-/usr/bin/docker rm %n
      ExecStartPre=/usr/bin/docker pull rmoriz/openra:latest
      ExecStart=/usr/bin/docker run \
        -p 1234:1234 \
        -e Name="EU | NL | pescheck.io/vacancies | #${current_server}" \
        -e Mod=ra \
        -e ListenPort="1234" \
        --name %n \
        rmoriz/openra:latest

      [Install]
      WantedBy=default.target

runcmd:
  - "chown -R ${user}:${user} /home/${user}/.openttd"
  - "systemctl enable docker.openttd"
  - "systemctl start docker.openttd"
  - "systemctl enable docker.openra"
  - "systemctl start docker.openra"

output:
  {
    all: '| tee -a /var/log/cloud-init-output.log'
  }